
name: Autograding
on: [push]
jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-python@v2
            with:
                python-version: 3.8
          - uses: actions/checkout@v2
          - uses: education/autograding@v1    
